-- MySQL Script generated by MySQL Workbench
-- Sat Apr  3 17:02:43 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema task10
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema task10
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `task10` DEFAULT CHARACTER SET utf8 ;
USE `task10` ;

-- -----------------------------------------------------
-- Table `task10`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `task10`.`product` (
  `maker` VARCHAR(10) NOT NULL,
  `model` VARCHAR(50) NOT NULL,
  `type` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`model`),
  UNIQUE INDEX `model_UNIQUE` (`model` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `task10`.`laptop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `task10`.`laptop` (
  `code` INT NOT NULL,
  `model` VARCHAR(50) NOT NULL,
  `speed` SMALLINT NOT NULL,
  `ram` SMALLINT NOT NULL,
  `hd` REAL NOT NULL,
  `price` DECIMAL(5,2) NOT NULL,
  `SCREEN` TINYINT NOT NULL,
  PRIMARY KEY (`code`),
  UNIQUE INDEX `model_UNIQUE` (`model` ASC),
  CONSTRAINT `mod1`
    FOREIGN KEY (`model`)
    REFERENCES `task10`.`product` (`model`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `task10`.`pc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `task10`.`pc` (
  `code` INT NOT NULL,
  `model` VARCHAR(50) NOT NULL,
  `speed` SMALLINT NOT NULL,
  `ram` SMALLINT NOT NULL,
  `hd` REAL NOT NULL,
  `cd` VARCHAR(10) NOT NULL,
  `price` DECIMAL(5,2) NOT NULL,
  PRIMARY KEY (`code`),
  UNIQUE INDEX `model_UNIQUE` (`model` ASC),
  CONSTRAINT `mod2`
    FOREIGN KEY (`model`)
    REFERENCES `task10`.`product` (`model`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `task10`.`printer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `task10`.`printer` (
  `code` INT NOT NULL,
  `model` VARCHAR(50) NOT NULL,
  `color` CHAR(1) NOT NULL,
  `type` VARCHAR(10) NOT NULL,
  `price` DECIMAL(5,2) NOT NULL,
  PRIMARY KEY (`code`),
  UNIQUE INDEX `model_UNIQUE` (`model` ASC),
  CONSTRAINT `mod`
    FOREIGN KEY (`model`)
    REFERENCES `task10`.`product` (`model`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
